# Generated by Django 5.0.6 on 2026-04-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributioncategory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='distributioncategory',
            name='cat_type',
            field=models.CharField(choices=[('fixed', 'Monto fijo desde costo del producto'), ('percent', 'Porcentaje del precio de venta'), ('remainder', 'Resto / Utilidad neta')], default='percent', max_length=20),
        ),
        migrations.AlterField(
            model_name='distributioncategory',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solo si cat_type = percent', max_digits=5),
        ),
    ]
