# Generated by Django 5.0.6 on 2026-04-05 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_cart_options_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razon_social', models.CharField(default='', max_length=200)),
                ('rut', models.CharField(default='', max_length=12)),
                ('giro', models.CharField(default='', max_length=200)),
                ('direccion', models.CharField(default='', max_length=300)),
                ('ciudad', models.CharField(default='Chile', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='billing/')),
                ('ultimo_numero_boleta', models.PositiveIntegerField(default=0)),
                ('ultimo_numero_factura', models.PositiveIntegerField(default=0)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
            },
        ),
        migrations.CreateModel(
            name='TributaryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('nota_credito', 'Nota de Crédito')], default='boleta', max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('folio', models.CharField(max_length=20)),
                ('receptor_nombre', models.CharField(blank=True, max_length=200)),
                ('receptor_rut', models.CharField(blank=True, max_length=12)),
                ('receptor_email', models.EmailField(blank=True, max_length=254)),
                ('receptor_giro', models.CharField(blank=True, max_length=200)),
                ('receptor_direccion', models.CharField(blank=True, max_length=300)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('anulado', 'Anulado'), ('enviado', 'Enviado por email')], default='emitido', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='billing/pdfs/')),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tributary_document', to='orders.order')),
            ],
            options={
                'verbose_name': 'Documento Tributario',
                'verbose_name_plural': 'Documentos Tributarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
