# Generated by Django 5.0.6 on 2026-04-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingconfig',
            name='direccion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='giro',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='rut',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
