# Generated by Django 5.0.6 on 2026-04-05 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_cart_options_alter_order_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puntos_por_peso', models.DecimalField(decimal_places=4, default=0.01, help_text='Puntos ganados por cada $1 gastado. Ej: 0.01 = 1 punto por $100', max_digits=8)),
                ('peso_por_punto', models.DecimalField(decimal_places=2, default=1.0, help_text='Valor en pesos de cada punto al canjear. Ej: 1.0 = 1 punto = $1', max_digits=8)),
                ('minimo_canje', models.PositiveIntegerField(default=500, help_text='Mínimo de puntos para poder canjear')),
                ('expiracion_dias', models.PositiveIntegerField(default=365, help_text='Días hasta que expiran los puntos (0 = nunca)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Fidelización',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puntos_totales', models.PositiveIntegerField(default=0)),
                ('puntos_canjeados', models.PositiveIntegerField(default=0)),
                ('puntos_expirados', models.PositiveIntegerField(default=0)),
                ('nivel', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de Fidelización',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('earn', 'Ganados'), ('redeem', 'Canjeados'), ('expire', 'Expirados'), ('adjust', 'Ajuste manual')], max_length=20)),
                ('puntos', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Transacción de Puntos',
                'ordering': ['-created_at'],
            },
        ),
    ]
