# Generated by Django 5.0.6 on 2026-03-24 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('mercadopago', 'MercadoPago'), ('transbank', 'Transbank'), ('flow', 'Flow'), ('transfer', 'Transferencia bancaria'), ('cash', 'Pago manual')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('transaction_id', models.CharField(blank=True, help_text='ID de la transacción del proveedor de pago', max_length=255)),
                ('provider_reference', models.CharField(blank=True, help_text='Referencia adicional del proveedor', max_length=255)),
                ('payment_url', models.URLField(blank=True, help_text='URL de pago (ej: checkout MercadoPago)')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Respuesta completa del proveedor de pago', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
