# Generated by Django 5.0.6 on 2026-03-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='preference_id',
            field=models.CharField(blank=True, help_text='ID de preferencia MP o PayPal order ID', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('mercadopago_cl', 'MercadoPago Chile'), ('mercadopago_ar', 'MercadoPago Argentina'), ('paypal', 'PayPal'), ('global66', 'Transferencia Global66'), ('transfer', 'Transferencia bancaria'), ('cash', 'Pago manual')], default='transfer', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, help_text='URL de checkout del proveedor'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('in_review', 'En revisión')], default='pending', max_length=20),
        ),
    ]
