# Generated by Django 5.0.6 on 2026-04-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo real del producto (capital invertido)', max_digits=12, null=True),
        ),
    ]
