# Generated by Django 5.0.6 on 2026-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_min',
            field=models.PositiveIntegerField(default=5, help_text='Alerta cuando el stock baje de este nivel', verbose_name='Stock mínimo'),
        ),
    ]
